on: [push]

env:
  node-version: 20.x

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Install Madlib
        run: npm install -g @madlib-lang/madlib@0.23.13

      - name: Display Madlib version
        run: madlib -v

      - name: Install Madlib Modules
        run: madlib install

      - name: Generate .docs
        run: mkdir .docs

      - name: Run tests
        run: madlib test --coverage

      - name: Push coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .coverage/lcov.info
