name: 'Publish new version'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish ( ex: v0.0.1 )'
        required: true

env:
  node-version: 14.x


jobs:
  check-version:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: |
            MADLIB_PKG_VERSION="v$(cat madlib.json | grep version | cut -d":" -f2 | cut -d"\"" -f2)"
            TAG_NAME=${{ github.event.inputs.version }}
            if [ "$TAG_NAME" = "$MADLIB_PKG_VERSION" ]; then
              echo "Versions match"
            else
              echo "Versions in madlib.json is not ${TAG_NAME}"
              exit 1
            fi

  release:
    needs: check-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: "Changelog: generate changelog"
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.4.1
        with:
          presets: "conventionalcommits"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-on-empty: false
          output-file: false
          tag-prefix: 'v'
          skip-commit: true
          skip-version-file: true

      - name: "Delete created tag from changelog"
        run: |
          git push --delete origin v${{ steps.changelog.outputs.version }}
          git tag -d v${{ steps.changelog.outputs.version }}

      - name: "Create Release"
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false
